/**
 * Mock Data Generator
 * Generates realistic workflow data for development and demos
 */

class MockDataGenerator {
    /**
     * Generate mock workflow issues
     */
    static generateWorkflowIssues(count = 30) {
        const issues = [];
        const today = new Date();

        for (let i = 0; i < count; i++) {
            const date = new Date(today);
            date.setDate(date.getDate() - i);

            const commitsToday = Math.floor(Math.random() * 15) + 1;
            const prsToday = Math.floor(Math.random() * 3);
            const openIssues = Math.floor(Math.random() * 5);

            issues.push({
                number: 1000 + i,
                title: `🌟 Daily Repository Snapshot - ${date.toLocaleDateString()}`,
                created_at: date.toISOString(),
                html_url: `https://github.com/ANISHTWAGLE/Anish/issues/${1000 + i}`,
                body: this.generateIssueBody(date, commitsToday, prsToday, openIssues)
            });
        }

        return issues;
    }

    /**
     * Generate realistic issue body content
     */
    static generateIssueBody(date, commitsToday, prsToday, openIssues) {
        const commitMessages = [
            'feat: implement new dashboard component',
            'fix: resolve API integration bug',
            'style: update UI theme and colors',
            'refactor: optimize data processing logic',
            'docs: update README with new features',
            'test: add unit tests for analytics engine',
            'chore: update dependencies',
            'perf: improve chart rendering performance'
        ];

        const commits = Array.from({ length: commitsToday }, (_, i) => {
            const time = `${Math.floor(Math.random() * 12) + 8}:${Math.floor(Math.random() * 60).toString().padStart(2, '0')}`;
            const message = commitMessages[Math.floor(Math.random() * commitMessages.length)];
            return `✅ ${time} UTC: "${message}"`;
        }).join('\n');

        const insights = [
            '🔥 High development velocity with consistent daily commits',
            '🎨 Excellent code quality and design patterns',
            '⚙️ Smooth CI/CD pipeline execution',
            '💾 Effective data management and caching strategies',
            '📚 Comprehensive documentation updates'
        ];

        const randomInsights = insights.sort(() => 0.5 - Math.random()).slice(0, 3);

        return `# 🌟 Daily Repository Snapshot
Repository: Anish Todo List | Date: ${date.toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}
Time: ${Math.floor(Math.random() * 24)}:${Math.floor(Math.random() * 60).toString().padStart(2, '0')} UTC

## 📈 Activity Highlights
🚀 Commits Made Today: ${commitsToday} focused improvements

${commits}

🔀 Pull Requests: ${prsToday} ${prsToday > 0 ? 'merged' : 'in progress'}

${prsToday > 0 ? `✅ PR #${Math.floor(Math.random() * 100)}: Feature implementation - Successfully merged to main` : ''}

📋 Open Issues: ${openIssues} tracking items

🏷️ Releases: ${Math.random() > 0.9 ? '1 new release' : 'None yet'}

## 💡 Key Insights
What's Going Phenomenal! 🎉

${randomInsights.join('\n')}

Areas Trending Upward:

🎯 Feature-rich functionality with clean architecture
🔄 Consistent iteration and improvement
🚀 Main branch stability maintained

Attention Needed (Minor):

${openIssues > 3 ? '🛠️ Several open issues - consider prioritization' : '✅ Issue backlog well managed'}
📖 Documentation could be expanded

## 🎯 Next Steps & Recommendations
🎉 Celebrate the Wins!

Today's delivery is ${commitsToday > 10 ? 'impressive' : 'solid'} - ${commitsToday} commits!
${prsToday > 0 ? 'PRs merged successfully' : 'Continue feature development'}

📖 Showcase Your Work (Medium Priority)

Expand documentation
Add screenshots and demos
Document architecture decisions

🔧 Polish & Ship (Low Priority)

Consider release tagging
Cross-browser testing
Performance optimization

## 💼 Project Summary
The project is showing ${commitsToday > 10 ? 'excellent' : 'good'} momentum with ${commitsToday} commits delivered. Code quality is strong with proper architecture patterns and state management.

Status: ${commitsToday > 10 ? 'Excellent ✨' : 'Good 👍'}
${prsToday > 0 ? 'Features merged and deployed!' : 'Development in progress'}

---
Generated by Daily Repo Status Workflow
Status: ${openIssues} open issues | ${prsToday} merged PR${prsToday !== 1 ? 's' : ''} today | ${commitsToday} commits`;
    }

    /**
     * Generate mock commits
     */
    static generateCommits(count = 100) {
        const commits = [];
        const today = new Date();
        const authors = ['Alice Johnson', 'Bob Smith', 'Carol Williams', 'David Brown'];
        const messages = [
            'feat: add new analytics dashboard',
            'fix: resolve data fetching issue',
            'style: update component styling',
            'refactor: improve code organization',
            'docs: update API documentation',
            'test: add integration tests',
            'chore: update dependencies',
            'perf: optimize rendering performance'
        ];

        for (let i = 0; i < count; i++) {
            const date = new Date(today);
            date.setDate(date.getDate() - Math.floor(i / 3));
            date.setHours(Math.floor(Math.random() * 24));

            commits.push({
                sha: Math.random().toString(36).substring(7),
                message: messages[Math.floor(Math.random() * messages.length)],
                author: authors[Math.floor(Math.random() * authors.length)],
                date: date.toISOString(),
                url: `https://github.com/ANISHTWAGLE/Anish/commit/${Math.random().toString(36).substring(7)}`
            });
        }

        return commits;
    }

    /**
     * Generate mock pull requests
     */
    static generatePullRequests(count = 20) {
        const prs = [];
        const today = new Date();
        const authors = ['alice', 'bob', 'carol', 'david'];
        const titles = [
            'Add new dashboard feature',
            'Fix API integration bug',
            'Update UI components',
            'Refactor data layer',
            'Improve performance',
            'Add unit tests',
            'Update documentation'
        ];

        for (let i = 0; i < count; i++) {
            const created = new Date(today);
            created.setDate(created.getDate() - Math.floor(Math.random() * 30));

            const merged = Math.random() > 0.3 ? new Date(created) : null;
            if (merged) {
                merged.setDate(created.getDate() + Math.floor(Math.random() * 7));
            }

            prs.push({
                number: 100 + i,
                title: titles[Math.floor(Math.random() * titles.length)],
                state: merged ? 'closed' : 'open',
                author: authors[Math.floor(Math.random() * authors.length)],
                created: created.toISOString(),
                updated: merged ? merged.toISOString() : new Date().toISOString(),
                merged: merged ? merged.toISOString() : null,
                url: `https://github.com/ANISHTWAGLE/Anish/pull/${100 + i}`
            });
        }

        return prs;
    }

    /**
     * Generate mock contributors
     */
    static generateContributors() {
        return [
            { login: 'alice', contributions: 150 },
            { login: 'bob', contributions: 89 },
            { login: 'carol', contributions: 45 },
            { login: 'david', contributions: 23 }
        ];
    }

    /**
     * Generate complete mock dataset
     */
    static generateCompleteDataset() {
        return {
            workflowIssues: this.generateWorkflowIssues(30),
            commits: this.generateCommits(100),
            pullRequests: this.generatePullRequests(20),
            contributors: this.generateContributors()
        };
    }
}

export default MockDataGenerator;
